### ISSUE TITLE
1.12.2 Connection issue

### ISSUE THREAD

**Issue by cunningb** [LilyPad/Bukkit-Connect#41]
I am unable to connect to my server using a 1.12.2 client.

I have tried on a paperspigot 1.12.1 + viaversion 1.3.0 and a paperspigot 1.12.2 server
Both times I have been using [BukkitConnect v121](http://ci.lilypadmc.org/job/Bukkit-Connect/121/)
I saw there was no changes listed between 120 and 121, so I also tried the 120 build with no luck.

On my server, the Bukkit-Connect plugin prints this error when attempting to connect.
```
java.lang.NoSuchFieldException: isOnlineMode
    at java.lang.Class.getDeclaredField(Class.java:2070)
    at lilypad.bukkit.connect.util.ReflectionUtils.setFinalField(ReflectionUtils.java:37)
    at lilypad.bukkit.connect.login.LoginNettyInjectHandler.handlePacketLoginStart(LoginNettyInjectHandler.java:198)
    at lilypad.bukkit.connect.login.LoginNettyInjectHandler.packetReceived(LoginNettyInjectHandler.java:37)
    at lilypad.bukkit.connect.injector.NettyDecoderHandler.decode(NettyDecoderHandler.java:24)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.setNativeProtocol(InitialPacketDecoder.java:194)
    at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decode(InitialPacketDecoder.java:149)
    at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:104)
    at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:30)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:748)
```
I'm kicked from the server saying `Outdated Server! I'm still on 1.12.2`

If I downgrade to a 1.12 client then I am able to connect briefly before being kicked for a possibly different issue.

```
logged in with entity id 2 at ([world]-812.971494864038, 4.0, 16.679425994224676)
lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(8) exceeds writerIndex(2): PooledUnsafeDirectByteBuf(ridx: 1, widx: 2, cap: 256)
```

I'm going to continue to look into the possibility of this being an issue on my end, since I don't see anyone else having problems with Bukkit-Connect on 1.12.2, but I figured you might want the stack trace at least.

**Comment by cunningb** [comment]
This does actually appear to be an issue on my end. I made a new server with only paperspigot 1.12.2 and Bukkit-Connect v121, and I was able to join without issue. I'll start reintroducing plugins and I'll update with anything useful I find.

Sorry, I should have made a barebones server before creating the issue.

**Comment by coelho** [comment]
No problem. Maybe it's ProtocolSupport or ProtocolLib incompatibility? Let me know :) @cunningb

**Comment by cunningb** [comment]
I believe it is an issue with ProtocolSupport

The version of ProtocolSupport that supports a 1.12.1 server seems to be incompatible with Bukkit-Connect. If I use them together I get that error. 

Everything seems to work if I use paperspigot 1.12.2 with ProtocolSupport 4.28-dev build #171, and Bukkit-Connect v121/120, but if I try to use another combination I run into issues.

I have a different server which runs 1.12 and allows 1.12.2 clients to join. That runs Bukkit-Connect v120 and ProtocolSupport v4.26-dev

Seems a little odd that it broke somewhere between supporting 1.12 and 1.12.1/2, but at least I've figured it out a bit.
