### ISSUE TITLE
Error when trying to connect to local SQL

### ISSUE THREAD

**Issue by Shuaiouke** [LilyPad/Bukkit-Connect#61]
so Im new with network syncing plugins and Im trying to sync LP between 2 servers, but when I start lilypad with the ip(17.0.0.1) and port 3306 and log in details of root, but when I start it, it spams the console with this

Caused by: java.lang.IndexOutOfBoundsException: readerIndex(47) + length(100) exceeds writerIndex(74): UnpooledHeapByteBuf(ridx: 47, widx: 74, cap: 74)
[10:11:00 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175)
[10:11:00 WARN]:        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:676)
[10:11:00 WARN]:        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:684)
[10:11:00 WARN]:        at lilypad.packet.common.util.BufferUtils.readString(BufferUtils.java:50)
[10:11:00 WARN]:        at lilypad.packet.connect.impl.RedirectPacketCodec.decode(RedirectPacketCodec.java:14)
[10:11:00 WARN]:        at lilypad.packet.connect.impl.RedirectPacketCodec.decode(RedirectPacketCodec.java:7)
[10:11:00 WARN]:        at lilypad.packet.common.PacketDecoder.decode(PacketDecoder.java:29)
[10:11:00 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[10:11:00 WARN]:        ... 18 more
<Insert the retry thing because I dumb and forgot to copy but also lazy to go back and get it>

did I do anything wrong or is there conflicting plugins?

**Comment by coelho** [comment]
LilyPad does not use MySQL. You need to setup a Connect Server to use LilyPad: http://ci.lilypadmc.org/job/Go-Server-Connect/
