### ISSUE TITLE
Plugin is unable to enable.

### ISSUE THREAD

**Issue by bpx573** [LilyPad/Bukkit-Connect#62]
The newest version of bukkit-connect does not work with spigot 1.16.5. There are 2 errors present on startup. It also doesnt work with the latest java 16.

Errors pastebin: https://pastebin.com/j5AntRca
I will copy and paste the errors too incase the pastebin breaks.
1st error:
[12:28:54] [Server thread/WARN]: Legacy plugin LilyPad-Connect v132 does not specify an api-version.
[12:28:54] [Server thread/WARN]: java.lang.NoSuchFieldException: modifiers
[12:28:54] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
[12:28:54] [Server thread/WARN]: 	at lilypad.bukkit.connect.util.ReflectionUtils.<clinit>(ReflectionUtils.java:19)
[12:28:54] [Server thread/WARN]: 	at lilypad.bukkit.connect.hooks.SpigotHook.<init>(SpigotHook.java:23)
[12:28:54] [Server thread/WARN]: 	at lilypad.bukkit.connect.ConnectPlugin.<init>(ConnectPlugin.java:25)
[12:28:54] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:28:54] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[12:28:54] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[12:28:54] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[12:28:54] [Server thread/WARN]: 	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
[12:28:54] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350)
[12:28:54] [Server thread/WARN]: 	at java.base/java.lang.Class.newInstance(Class.java:642)
[12:28:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:94)
[12:28:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153)
[12:28:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414)
[12:28:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322)
[12:28:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393)
[12:28:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281)
[12:28:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[12:28:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
[12:28:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[12:28:54] [Server thread/INFO]: [LilyPad-Connect] Loading LilyPad-Connect v132
 
2nd error: [12:28:54] [Server thread/INFO]: [LilyPad-Connect] Enabling LilyPad-Connect v132*
[12:28:54] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.setInt(Object, int)" because "lilypad.bukkit.connect.util.ReflectionUtils.FIELD_MODIFIERS" is null
[12:28:54] [Server thread/WARN]: 	at lilypad.bukkit.connect.util.ReflectionUtils.setFinalField(ReflectionUtils.java:41)
[12:28:54] [Server thread/WARN]: 	at lilypad.bukkit.connect.injector.NettyInjector.injectAndFindPort(NettyInjector.java:46)
[12:28:54] [Server thread/WARN]: 	at lilypad.bukkit.connect.ConnectPlugin.onEnable(ConnectPlugin.java:88)
[12:28:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:28:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[12:28:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[12:28:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[12:28:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[12:28:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:282)
[12:28:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[12:28:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
[12:28:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[12:28:54] [Server thread/INFO]: [Connect] Unable to start plugin - unsupported version?

**Comment by WesJD** [comment]
This issue will be resolved in #63.

**Comment by coelho** [comment]
Resolved. 1.17 support added. Please view README as well:
https://github.com/LilyPad/Bukkit-Connect/blob/master/README.md
